// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCkbaFSzkN6olotVnCanlJ07GYOEPda1k',
    appId: '1:375895258875:web:8088331e15c7f3093fa25e',
    messagingSenderId: '375895258875',
    projectId: 'cd2-20223155-nguyentridung',
    authDomain: 'cd2-20223155-nguyentridung.firebaseapp.com',
    storageBucket: 'cd2-20223155-nguyentridung.firebasestorage.app',
    measurementId: 'G-J11G89BPNW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_IIqf3wHWKwpJudlhlpEm41LHZwxIi3E',
    appId: '1:375895258875:android:efce47bc9a1bd4193fa25e',
    messagingSenderId: '375895258875',
    projectId: 'cd2-20223155-nguyentridung',
    storageBucket: 'cd2-20223155-nguyentridung.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCf4MY6i8aLenoUeC7w2TarhHPTFu4dyl8',
    appId: '1:375895258875:ios:9d4d3c64831dd08d3fa25e',
    messagingSenderId: '375895258875',
    projectId: 'cd2-20223155-nguyentridung',
    storageBucket: 'cd2-20223155-nguyentridung.firebasestorage.app',
    iosBundleId: 'com.example.chuyende220223155Nguyentridung',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCf4MY6i8aLenoUeC7w2TarhHPTFu4dyl8',
    appId: '1:375895258875:ios:9d4d3c64831dd08d3fa25e',
    messagingSenderId: '375895258875',
    projectId: 'cd2-20223155-nguyentridung',
    storageBucket: 'cd2-20223155-nguyentridung.firebasestorage.app',
    iosBundleId: 'com.example.chuyende220223155Nguyentridung',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCkbaFSzkN6olotVnCanlJ07GYOEPda1k',
    appId: '1:375895258875:web:f4de5a65c59cf0223fa25e',
    messagingSenderId: '375895258875',
    projectId: 'cd2-20223155-nguyentridung',
    authDomain: 'cd2-20223155-nguyentridung.firebaseapp.com',
    storageBucket: 'cd2-20223155-nguyentridung.firebasestorage.app',
    measurementId: 'G-CZMTS9H64Q',
  );

}